### PR TITLE
linuxserver/docker-pydio#22 modifying the base Nginx config and addin…

### PR DESCRIPTION
**Pull request by thelamer**
Referenced from issue #22 . 

Updated the Nginx config and added a parameter for users setting their base URL in the Nginx file this value will also be picked up by pydio on first launch.

### CODE REVIEW

**Comment by sparklyballs** [comment]
sed'ing like that has the potential to overwrite settings for existing users that have manually added/changed that particular setting in their nginx config

**Comment by sparklyballs** [comment]
bunching up the spaces and leaving the # lines in doesn't solve the continuation lines warning

also this is on my list for updating to newer alpine

**Comment by thelamer** [comment]
The sed only replaces on first run which is why it replaces the string REPLACEHOSTNAME, unless that is the users hostname it would never conflict. 

It fixed the line warnings for me: 

```
Docker version 17.09.1-ce, build 19e2cf6
```

**Comment by sparklyballs** [comment]
I'm gonna close this but take the rewrite of the nginx config from the PR

as for the pydio url another issue that there is the possibility for is someone makes a typo on their URL or wants to change it

I shall make a note in the README about manually entering the server name field to allow for public link sharing to work properly

**Pull request closed without merging**
