### PR TITLE
Update nginx config

### PR DESCRIPTION
**Pull request by Pusnow**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

##  Thanks, team linuxserver.io

PR for solving #11 and reflect code review #12.

It also solves these problems (becaus rewrite rule changes):

* Make Pydio API works (used for Pydio Sync)
* Make WebDAV works

### CODE REVIEW

**Comment by aptalca** [comment]
Thanks this looks much better. We'll do some testing

**Comment by aptalca** [comment]
Jenkins please test this

**Comment by lucasdiedrich** [comment]
Guys, as i mentioned before, i had to change the file as proposed by @Pusnow , and my collabora started to work.

I'm wondering, should we change the file to reflect Pydio 8?

**Comment by tammon** [comment]
Why is this still not merged??? The current nginx site config with Pydio 6 settings breaks the api, webdav, ... because of the old pydio6 rewrite rules. This config makes the whole image unusable beside the plain web interface. This is related to #22 #2 #11 

Everybody encountering the same Issue with Pydio 7 and 8 with nginx having problems to access public shares, API and webdav: 

**Replace the file /config/nginx/site-confs/default (for linuxserver.io image) which contains the outdated Pydio 6 config for nginx with:**
```
##   ---- ATTENTION: Security Advice! ----
## This config is targeted for deployments running behind a reverse https proxy.
## Therefor it only exposes http over port 80 having all ssl statements and redirects disabled.
## If you expose Pydio directly to the internet consider using HTTPS in this config!
## To achieve that uncomment the ssl statements and the redirect from http to https.
## Full explanation on https://pydio.com/de/docs/kb/system/installing-debiannginx

#server {
#    listen 80;
#    ### Change the following line to match your website name
#    server_name YOUR_SERVER_NAME;
#    rewrite ^ https://$server_name$request_uri? permanent;
#}

server {
    #listen 443 ssl;
    listen 80;
    ### Change the following line to match your website name
    server_name YOUR_SERVER_NAME;
    root /config/www/pydio;
    index index.php;

    ### If you changed the maximum upload size in PHP.ini, also change it below
    client_max_body_size 20G;

    # Prevent Clickjacking
    add_header X-Frame-Options "SAMEORIGIN";

    # SSL Settings
    ### If you are using different names for your SSL certificate and key, change them below:
    #ssl on;
    #ssl_certificate /etc/nginx/ssl/nginx.crt;
    #ssl_certificate_key /etc/nginx/ssl/nginx.key;

    # This settings are destined to limit the supported crypto suites, this is optional and may restrict the availability of your website.
    #ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
    #ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    #add_header Strict-Transport-Security "max-age=16070400; includeSubdomains";

    keepalive_requests    10;
    keepalive_timeout     60 60;
    access_log /config/log/pydio/access_pydio7.log;
    error_log /config/log/pydio/error_pydio7.log;

    client_body_buffer_size 128k;
    # All non existing files are redirected to index.php
    if (!-e $request_filename){
        # For old links generated from Pydio 6
        rewrite ^/data/public/([a-zA-Z0-9_-]+)$ /public/$1? permanent;
        rewrite ^(.*)$ /index.php last;
    }

    # Manually deny some paths to ensure Pydio security
    location ~* ^/(?:\.|conf|data/(?:files|personal|logs|plugins|tmp|cache)|plugins/editor.zoho/agent/files) {
            deny all;
    }

    # Forward PHP so that it can be executed
    location ~ \.php$ {

            fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
            fastcgi_param  SERVER_SOFTWARE    nginx;
            fastcgi_param  QUERY_STRING       $query_string;
            fastcgi_param  REQUEST_METHOD     $request_method;
            fastcgi_param  CONTENT_TYPE       $content_type;
            fastcgi_param  CONTENT_LENGTH     $content_length;
            fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
            fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
            fastcgi_param  REQUEST_URI        $request_uri;
            fastcgi_param  DOCUMENT_URI       $document_uri;
            fastcgi_param  DOCUMENT_ROOT      $document_root;
            fastcgi_param  SERVER_PROTOCOL    $server_protocol;
            fastcgi_param  REMOTE_ADDR        $remote_addr;
            fastcgi_param  REMOTE_PORT        $remote_port;
            fastcgi_param  SERVER_ADDR        $server_addr;
            fastcgi_param  SERVER_PORT        $server_port;
            fastcgi_param  SERVER_NAME        $server_name;

            try_files $uri =404;
            fastcgi_pass 127.0.0.1:9000;
            
            ## this is from the orginial example for reference
            #fastcgi_pass unix:/run/php/php7.0-fpm.sock ;
    }

    # Enables Caching
    location ~* \.(ico|css|js)$ {
        expires 7d;
        add_header Pragma public;
        add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    }
}
```

_Pydio 7, Pydio 8, reverse Proxy, nginx, API, PydioSync, sync, not working, webdav, problem, linuxserver.io_

**Comment by sparklyballs** [comment]
@tammon you are aware that the config is in a mounted volume and can if required (and in some cases should) be edited to suit ?

**Comment by tammon** [comment]
@sparklyballs this is exactly what I did and what I wanted to encourage with the last post. :)
But what's the point of having a "plug&run" Docker image for Pydio (which this image claims to be) and then spending hours on debugging because it just uses an outdated config. In this case it is not a matter of "changing the config to suite my needs" instead it is "changing the outdated config in every deployment to work properly at all" (note: the current release of this image uses Pydio 8 with Pydio 6 configs). And as I read that there's already a pr from nearly a year ago, I asked myself why this obvious low-hanging-fruit wasn't merged months ago?

Besides that, sparklyballs is completely right: Because this is only a config bug, anybody who encounters the same problem can simply replace the conf file as described above stored in the config-volume or simply look at the proposed change of @Pusnow . :-)

**Comment by ncoder-1** [comment]
Any chance we could merge the properly working config file?

**Comment by aptalca** [comment]
In all honesty, it was my responsibility to review and test the new config, but got busy and then forgot about it. Apologies. It's back on my list now.

**Pull request closed without merging**
